### PR TITLE
Fix: Instruction for location of custom connector

### PR DESCRIPTION
**Pull request by eliempje**
Name of directory is changed to get this to work with PowerBI desktop.

### CODE REVIEW

**Comment by BentsiLeviav** [comment]
Hi @eliempje,

Thank you for your contribution! Could you please provide any clarification regarding this requirement?

On the [documentation page](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-connector-extensibility#custom-connectors), this path is still the default path used by Power BI.

**Comment by eliempje** [comment]
Indeed that still in that documentation.

Otherwise the custom connector doesn't work with PowerBI (installed from MicrsoftStore) e.g. Version: 2.123.742.0 64-bit (november 2023).

I've have put in a request there aswell:
https://github.com/MicrosoftDocs/powerbi-docs/issues/4907

**Comment by eliempje** [comment]
You've updated the documentation/readme already in another way

**Comment by BentsiLeviav** [comment]
FYI - the MS team has clarified the right path at https://github.com/MicrosoftDocs/powerbi-docs/issues/4907#issuecomment-1969978518. I created a PR in our doc repository to fix the wrong path ClickHouse/clickhouse-docs#2115

**Pull request closed without merging**
